import moment from 'moment';

const tableName = 'projects';

const seeds = [
  // ----------------------------------------- Projects from user: 4, profile: 1
  {
    id: 1,
    profile_id: 1,
    name: 'How to Organize Anything',
    role: 'Author',
    slug: null,
    tagline: '',
    organization: null,
    image_url: null,
    brief_description: '',
    full_description: '',
    is_professional: false,
    started_at: '2016-07-30T11:20+08:00',
    finished_at: '2016-08-02T21:33+08:00',
  },

  // ----------------------------------------- Projects from user: 4, profile: 2
  {
    id: 2,
    profile_id: 2,
    name: 'NSA',
    role: 'Top Secret Bit Flipper',
    slug: null,
    tagline: 'Alone in a tiny windowless room',
    organization: 'The Collective',
    image_url: null,
    brief_description: '',
    full_description: 'Steady months of isolation and obfuscation.',
    is_professional: true,
    started_at: '2004-05-01',
    finished_at: '2004-12-31',
  },
  {
    id: 3,
    profile_id: 2,
    name: 'DOT',
    role: 'Software Architect/Developer',
    slug: null,
    tagline: '',
    organization: 'The Collective',
    image_url: null,
    brief_description: '',
    full_description: '',
    is_professional: true,
    started_at: '2005-01-01',
    finished_at: '2006-03-05',
  },
  {
    id: 4,
    profile_id: 2,
    name: 'Deep Dark Secret',
    role: 'Software Architect/Developer',
    slug: null,
    tagline: 'Divulge your deep, dark secrets...',
    organization: 'Soloist',
    image_url: null,
    brief_description: '',
    full_description: '',
    is_professional: false,
    started_at: '2007-02-12',
    finished_at: '2007-08-30',
  },

  // ---------------------------------------- Projects from user: 8, profile: 11
  {
    id: 5,
    profile_id: 11,
    name: 'E - Project 001',
    role: null,
    slug: null,
    tagline: null,
    organization: null,
    image_url: null,
    brief_description: null,
    full_description: null,
    is_professional: true,
    started_at: '2017-01-01',
    finished_at: null,
  },
  {
    id: 6,
    profile_id: 11,
    name: 'J - Project 002',
    role: null,
    slug: null,
    tagline: null,
    organization: null,
    image_url: null,
    brief_description: null,
    full_description: null,
    is_professional: true,
    started_at: '2017-03-10',
    finished_at: '2017-03-29',
  },
  {
    id: 7,
    profile_id: 11,
    name: 'P - Project 003',
    role: null,
    slug: null,
    tagline: null,
    organization: null,
    image_url: null,
    brief_description: null,
    full_description: null,
    is_professional: true,
    started_at: '2017-03-13',
    finished_at: null,
  },
  {
    id: 8,
    profile_id: 11,
    name: 'W - Project 004',
    role: null,
    slug: null,
    tagline: null,
    organization: null,
    image_url: null,
    brief_description: null,
    full_description: null,
    is_professional: true,
    started_at: '2017-04-11',
    finished_at: '2017-11-09',
  },
  {
    id: 9,
    profile_id: 11,
    name: 'L - Project 005',
    role: null,
    slug: null,
    tagline: null,
    organization: null,
    image_url: null,
    brief_description: null,
    full_description: null,
    is_professional: true,
    started_at: '2017-06-02',
    finished_at: '2017-08-01',
  },
  {
    id: 10,
    profile_id: 11,
    name: 'T - Project 006',
    role: null,
    slug: null,
    tagline: null,
    organization: null,
    image_url: null,
    brief_description: null,
    full_description: null,
    is_professional: true,
    started_at: '2017-08-22',
    finished_at: null,
  },
  {
    id: 11,
    profile_id: 11,
    name: 'H - Project 007',
    role: null,
    slug: null,
    tagline: null,
    organization: null,
    image_url: null,
    brief_description: null,
    full_description: null,
    is_professional: true,
    started_at: '2017-09-03',
    finished_at: '2017-11-25',
  },
  {
    id: 12,
    profile_id: 11,
    name: 'A - Project 008',
    role: null,
    slug: null,
    tagline: null,
    organization: null,
    image_url: null,
    brief_description: null,
    full_description: null,
    is_professional: true,
    started_at: '2017-09-18',
    finished_at: '2017-09-22',
  },
  {
    id: 13,
    profile_id: 11,
    name: 'N - Project 009',
    role: null,
    slug: null,
    tagline: null,
    organization: null,
    image_url: null,
    brief_description: null,
    full_description: null,
    is_professional: true,
    started_at: '2017-10-01',
    finished_at: '2017-10-09',
  },
  {
    id: 14,
    profile_id: 11,
    name: 'K - Project 010',
    role: null,
    slug: null,
    tagline: null,
    organization: null,
    image_url: null,
    brief_description: null,
    full_description: null,
    is_professional: true,
    started_at: '2017-11-17',
    finished_at: null,
  },
];

exports.seed = function seed(knex, Promise) {
  return knex(tableName).del().then(() => {
    const time = moment().utc();

    return Promise.all(seeds.map((data) => {
      const timestamp = time.add(5, 'minutes');

      return knex(tableName).insert({
        ...data,
        created_at: timestamp,
        updated_at: timestamp,
      });
    }));
  });
};
